### ISSUE TITLE
LinkedIn button is not working

### ISSUE THREAD

**Issue by ViktorianoCZ** [alex-waage/web-portfolio#2]
I found very strange bug with the big green LinkedIn button, I would assume it should redirect me to your LinkedIn profile, but it does nothing. I'm very disappointed for this, because I really wanted to check out your LinkedIn profile and because of this bug I'm not able to.

**Comment by alex-waage** [comment]
I mean my LinkedIn is not so interesting, so I will not add to the code. It is what it is.
